/* eslint-disable react/function-component-definition */
import ClientLayout from './clientLayout';
import ServerRootLayout from './serverLayout';

export const metadata = {
  title: process.env.NEXT_PUBLIC_BRAND_NAME,
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <ServerRootLayout>
      <ClientLayout>{children}</ClientLayout>
    </ServerRootLayout>
  );
}
